dado_usuario = input('Digite algo: ')

tipo_primitivo = type(dado_usuario)
letra_maiuscula = dado_usuario.isupper()
alpha_numerico = dado_usuario.isalnum()
alpha = dado_usuario.isalpha()
decimal = dado_usuario.isdecimal()
letra_minuscula = dado_usuario.islower()
numerico = dado_usuario.isnumeric()
exibe_na_tela = dado_usuario.isprintable()
somente_espacos = dado_usuario.isspace()
capitalizada = dado_usuario.istitle()

print(f'Tipo primitivo: {tipo_primitivo}')
print(f'Letra maiúscula: {letra_maiuscula}')
print(f'Alfanumérico: {alpha_numerico}')
print(f'Alpha: {alpha}')
print(f'Decimal: {decimal}')
print(f'Letra minúscula: {letra_minuscula}')
print(f'Numerico: {numerico}')
print(f'É exibível na tela: {exibe_na_tela}')
print(f'Só tem espaços: {somente_espacos}')
print(f'Está capitalizada: {capitalizada}')
